### ISSUE TITLE
Detail instruction for build process on README.txt

### ISSUE THREAD

**Issue by james-yoo** [code-iai/ROSIntegration#120]
I am a newbie to UE4 so apologies if the question is trivial.
What should I do for following instruction?

![image](https://user-images.githubusercontent.com/23667624/79240255-80498d00-7eac-11ea-88b5-221d3ca15c31.png)

**Comment by Roman-Malinowski** [comment]
This tutorial helped me, I hope you will find it useful!
https://www.youtube.com/watch?v=WtfLfYY_k2Y&feature=emb_title

**Comment by james-yoo** [comment]
Roman-Malinowski,
Thank you for your reply. It was really useful tpis.
