### ISSUE TITLE
Missing Project Modules

### ISSUE THREAD

**Issue by basvangeuns** [code-iai/ROSIntegration#122]
When I try to open my C++ project after making the Plugins folder it gives me this error:
![Schermafdruk van 2020-04-28 12-24-36](https://user-images.githubusercontent.com/64194150/80477136-ba566c80-894b-11ea-8d82-b1f1ce420294.png)

When I click yes I get the following:
![Schermafdruk van 2020-04-28 12-25-22](https://user-images.githubusercontent.com/64194150/80477205-d8bc6800-894b-11ea-83b2-8af559ef0dc1.png)

My ROSIntegration folder looks like this:
![Schermafdruk van 2020-04-28 12-31-42](https://user-images.githubusercontent.com/64194150/80477496-4e283880-894c-11ea-843e-77f5dc5bbe67.png)

I'm on UE4 version 4.20.3. I tried a lot but nothing seems to help. Is there any way I can fix this?

**Comment by pannenkoek1908** [comment]
I have the same problem, no idea how to fix it! If anyone knows that would be great!

**Comment by Sanic** [comment]
Hi,
could you please checkout older commits of this Repo and try to build again? This would help us to nail down which commit introduced the breaking change.

**Comment by basvangeuns** [comment]
I tried everything from the older commits. I keep getting the following issue:

![Schermafdruk van 2020-04-29 14-39-21](https://user-images.githubusercontent.com/64194150/80597250-dcbdb800-8a27-11ea-8986-43af1bbd48fb.png)

**Comment by basvangeuns** [comment]
I solved it by adding `#include "IPAddress.h"` to TCPConnection.cpp
