### ISSUE TITLE
Is there a way to write to bag files?

### ISSUE THREAD

**Issue by corwinjs** [code-iai/ROSIntegration#129]
Hello,

I was wondering if your plugin provides a way to directly write to bag files like what is done in the first example here: http://wiki.ros.org/rosbag/Code%20API#cpp_api .

Thanks,
Corwin

**Comment by Sanic** [comment]
Hi Corwin,

unfortunately not directly. We are not including any direct ROS code in this plugin, but rather use http://wiki.ros.org/rosbridge_suite to communicate with ROS.
If somebody is able to include the ROS libraries into UE4, then we could not only record ROS bags, but also get rid of the whole rosbridge code. However, i didn't find a good way back in the day when i started this plugin.
