### ISSUE TITLE
Support for UE 4.16.x?

### ISSUE THREAD

**Issue by oscarmendezm** [code-iai/ROSIntegration#17]
Hi,

 I noticed support for 4.16.x was removed. Is there any reason for this? Can I revert back to a version that has it? 

I need to be able to use it with some existing projects that would be a pain to upgrade.

Thanks!

**Comment by oscarmendezm** [comment]
Hi Sanic, 

Thanks for the quick reply! I've tried this on UE4.16.3 on Windows 10. I get the following errors:

![ue16ros1](https://user-images.githubusercontent.com/2923369/35219708-a09ebe80-ff6b-11e7-9443-91c269b4c429.PNG)
![ue16ros2](https://user-images.githubusercontent.com/2923369/35219709-a0b29c70-ff6b-11e7-9db2-0e5580c7d827.PNG)

I am still getting to grips with UE, so I am not sure how to fix this.

Thanks

**Comment by Sanic** [comment]
Hi!
The first warning is normal if you've added the Plugin to your Unreal project, but haven't it build yet. The second box is the interesting one, but you and we need more details.
Please check how you can access your compile logs to see the actual error.

**Comment by oscarmendezm** [comment]
This is the log file I get when I make a new project and try to start it. 

[ROSTEST_v16.log](https://github.com/code-iai/ROSIntegration/files/1652314/ROSTEST_v16.log)

I can't seem to find any reference to your code, instead it complains about some other stuff. However, if I remove the plugin the project starts without any issues.

**Comment by Sanic** [comment]
Hi @oscarmendezm 
Please have a look at https://github.com/code-iai/ROSIntegration/issues/19
Did you use a Blueprint project in your previous tests?
Can your issue be solved when you start with a fresh C++ Unreal Project?
