### ISSUE TITLE
How can I solve the problem of `sensor_msgs/CameraInfo does not have a field d`

### ISSUE THREAD

**Issue by pisces365** [code-iai/ROSIntegration#186]
I install the plugin of ROSIntegrationVision and I add the VisionActor into the 3D world.
But when I click run,the ros bridge show the error
`[ERROR] [1668582258.304523]: [Client 0] [id: publish:/unreal_ros/camera_info:50] publish: Message type sensor_msgs/CameraInfo does not have a field d`
I do not know where and how can I fix this.
So I wish someone can help me, thanks a lot!

I use Ubuntu 18.04 and UE 4.26.2, here is some image
![image](https://user-images.githubusercontent.com/41956859/202125870-735bff45-be16-4748-90f6-aee8149ec5b6.png)
![image](https://user-images.githubusercontent.com/41956859/202126140-fae40744-a679-4bd3-ba5f-f83756c2640d.png)

**Comment by Hemofektik** [comment]
Looks like the elements are not capital letters in the [serialization code ](https://github.com/code-iai/ROSIntegration/blob/d0018d501203b80fcf4df0b437fa6bc6aed77172/Source/ROSIntegration/Private/Conversion/Messages/sensor_msgs/SensorMsgsCameraInfoConverter.h#L61-L64) as they should be according to the [message definition](https://docs.ros.org/en/lunar/api/sensor_msgs/html/msg/CameraInfo.html).

**Comment by pisces365** [comment]
> Looks like the elements are not defined in capital letters in the [serialization code ](https://github.com/code-iai/ROSIntegration/blob/d0018d501203b80fcf4df0b437fa6bc6aed77172/Source/ROSIntegration/Private/Conversion/Messages/sensor_msgs/SensorMsgsCameraInfoConverter.h#L61-L64) as they should be according to the [message definition](https://docs.ros.org/en/lunar/api/sensor_msgs/html/msg/CameraInfo.html).

It seems that the problem has been solved. Thank you very much
