### ISSUE TITLE
Failed to build ROSIntegration on UE5 5.3.2 linux

### ISSUE THREAD

**Issue by ysdemiranda** [code-iai/ROSIntegration#208]
Hello,

I successfully built the ROSintegration plugin on Linux + Unreal Engine 5 by making a minor change to one of the source files.

For reference, this is one line of compilation output before making the change:

`In file included from /home/yasja/[REDACTED]/Plugins/ROSIntegration/Intermediate/Build/Linux/x64/UnrealEditor/Development/ROSIntegration/Module.ROSIntegration.cpp:122:
/home/yasja/[REDACTED]/Plugins/ROSIntegration/Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp:28:48: error: overload resolution selected deleted operator '<<'
                std::cout << "Given IP address is invalid: " << *address << std::endl;`

Which blocked the plugin from compiling.

Changing the line mentioned from
`std::cout << "Given IP address is invalid: " << *address << std::endl;`
to
`std::cout << "Given IP address is invalid: " << TCHAR_TO_UTF8(*address) << std::endl;`

Fixed the issue.

Best Regards,

Yasja

**Comment by aangert-anduril** [comment]
This fixed it for me too, it would be great to have a Pull Request for this feature!

**Comment by aangert-anduril** [comment]
Merged to master here: https://github.com/code-iai/ROSIntegration/pull/210

Thanks for helping out @ysdemiranda
