### ISSUE TITLE
Rebuild from Source...

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [code-iai/ROSIntegration#25]
Good afternoon again, 

I write you because some days ago I had the ROSIntegration and ROSIntegrationVision totally installed but due to some failure on my project I had to delete and create a new onw.

Now I am trying to install ROSIntegration and I cannot because I get the following failure. 

![image](https://user-images.githubusercontent.com/35638894/39086714-9923d05c-4596-11e8-893a-e7d318dfac93.png)

For sure, I click YES and the message is as follows: 

![image](https://user-images.githubusercontent.com/35638894/39086722-b3499c5a-4596-11e8-8b64-304331951988.png)

I try to rebuild and generate the project files from source but no good results.

Could you please help me? 

I have seen that more people had this issue but using another UE4 version.

Thanks a lot.

Best regards.

**Comment by Hemofektik** [comment]
Hi, which version of UE4 do you use? Additionally the generation of project files output logs that could help to identify the issue.

**Comment by yskim041** [comment]
It's because there are some declarations of `UPROPERTY` without any explicit Category specifier. In this case, when you build from source, you will be able to find error messages like this:
```
LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
```

**Comment by yskim041** [comment]
If you want to build from soure on Linux, you need to fix the declarations of `UPROPERTY` that are exposed to the editor or blueprints without any explicit Category specifier.

For example,
https://github.com/code-iai/ROSIntegration/blob/7376006abc8811454fddc1d8609ffd33f34a538e/Source/ROSIntegration/Classes/TFBroadcastComponent.h#L34
should be like
```
UPROPERTY(EditAnywhere, Category = "explicit specifier")
```

**Comment by Hemofektik** [comment]
It should compile again on linux. Keep in mind that this plugin is not an Engine plugin and should be build with your custom project and not put into the Engine/Plugins Folder.
