### ISSUE TITLE
rosbridge2cpp compile errors when building plugin

### ISSUE THREAD

**Issue by jacobdeery** [code-iai/ROSIntegration#28]
I'm using Unreal 4.18.3 on Ubuntu 16.04. I've done the following:

1. Create a new C++ Unreal project.
2. Clone this repo into the `<project>/Plugins` directory.
3. Enable the plugin through the editor menu.
4. Restart the editor in order to build the plugin.

The build fails during the restart. Looking at the log, I found the following relevant errors/warnings:
[unreal_build_errors.txt](https://github.com/code-iai/ROSIntegration/files/1988202/unreal_build_errors.txt)

**Comment by jacobdeery** [comment]
This seems to be a C++11 issue, from what I can tell. `std::function::target` was only introduced in C++11, and isn't described as one of the C++11 features that Unreal supports ([here](https://docs.unrealengine.com/en-us/Programming/Development/CodingStandard#c++11andmodernlanguagesyntax)).

**Comment by Hemofektik** [comment]
I did not test the latest changes on linux yet, sorry. I will try to fix that as soon as I can.

**Comment by dawgster** [comment]
A fix would be greatly appreciated! Thanks

**Comment by robbeofficial** [comment]
same error on ubuntu 18.05 / Unreal 4.19.1 (clang 5.0.1)

**Comment by Hemofektik** [comment]
Hi, as soon as the PR #29 is merged, it should work for you again. Sorry for the inconvenience.

**Comment by Hemofektik** [comment]
Hi, please verify whether this is fixed for you!

**Comment by jacobdeery** [comment]
Compiles correctly now, thanks!

**Comment by Sanic** [comment]
Thanks @Hemofektik for fixing this in your PR.
