### ISSUE TITLE
FROSTime Portability

### ISSUE THREAD

**Issue by tim37021** [code-iai/ROSIntegration#43]
there's no guarantee that epoch is 1970 on high_resolution_clock.
Most implementation typedef/using high_resolution_clock as steady_clock or system_clock

on my computer epoch is boot time, which make the sensor_Msgs timeout

**Comment by tim37021** [comment]
https://github.com/code-iai/ROSIntegration/blob/2dbc4be2edcb10c534e105d18132cc214734414d/Source/ROSIntegration/Public/ROSTime.h#L11

**Comment by Hemofektik** [comment]
Good point. Any idea how to fix that in a performance optimal manner?

**Comment by Hemofektik** [comment]
Good Point, I provided a fix in #44 that also includes the ability to simulate the clock

**Comment by Sanic** [comment]
PR #44 has been merged already. Closing this issue
