### ISSUE TITLE
Compile issue with new project

### ISSUE THREAD

**Issue by DaniloCaporale** [code-iai/ROSIntegration#45]
Hi all,

I followed the instructions in the README but I keep getting this error when compiling from the Unreal editor:

```
/home/user/Documents/Unreal Projects/MyProject2/Source/MyProject2/MyActor.cpp:7:10: fatal error: 'ROSIntegration/Classes/RI/Topic.h' file not found
```

Same happens if I try to compile from terminal.

I tried running (both with UE4Editor closed or open) the following
```
/path/to/UnrealEngine/GenerateProjectFiles.sh /path/to/Myproject2.uproject
```
as stated in the README but it didn't seem to fix the problem for me. Is this the right way to update the build system to link against the new plugin? Maybe some other option to give to GenerateProjectFiles script?
I am kinda new to Unreal so apologies if the question is trivial.

**Comment by Hemofektik** [comment]
Hi,

did you add ROSIntegration to your PrivateDependencyModuleNames of your MyProject2.Build.cs?

`PrivateDependencyModuleNames.AddRange(new string[] { "ROSIntegration" });`

**Comment by DaniloCaporale** [comment]
Worked like a charme! Thanks @Hemofektik!
