### ISSUE TITLE
Point of clarification on "Generate Project files" in readme

### ISSUE THREAD

**Issue by btwolfe** [code-iai/ROSIntegration#58]
Might want to clarify the language in the readme to say that generating project files for UE4 to resolve include path problems for the plugin is done by right clicking on the associated .uproject file in file explorer (at least for Windows 10) to get the "Generate Visual Studio project files" command. Don't know how this would be done in Linux.

**Comment by Sanic** [comment]
Hi! Thanks for the hint. I've added some links.
