### ISSUE TITLE
Matching Motion in Gazebo and UE4

### ISSUE THREAD

**Issue by smithan7** [code-iai/ROSIntegration#71]
I am working on a project where I am simulating the cameras in UE4 and some of the sensors in Gazebo, e.g., IMU/GPS/Magentometer using the Hector Package, and therefore need the quadcopter to move in Gazebo identically to how it does in UE4. I think I can 'hack' a solution by controlling the quad in Gazebo and subscribing to the Gazebo published odometry topic in UE4 then 'teleporting' the quad to the published odom topic. However, I am wondering if there is a cleaner or suggested way to accomplish this.

Thanks

**Comment by madratman** [comment]
https://bitbucket.org/osrf/gzue4bridge/wiki/Home might be something to look at.
I'm interested in this as well

**Comment by Sanic** [comment]
Hi!

I would look into the tf2 Package (http://wiki.ros.org/tf2) which is also supported by this Plugin.
You could then try to publish the pose of your quad in UE4 to the TF topic, read that pose from gazebo and then set up the quad there accordingly.
