### ISSUE TITLE
ROSIntegration.uplugin is not being compiled

### ISSUE THREAD

**Issue by kamilhassaan** [code-iai/ROSIntegration#77]
I have been trying to connect ROS with **Unreal 4.20.3** but all my tries go in vain. The plugins folder was not present by default when the project was created. I created this manually in the directory and created another folder inside plugins named **ROSIntegration**. I pasted **ROSIntegration.uplugin** inside **ROSIntegration** folder. After that when I start the project, i get the following messages:
_**The following modules re missing or built with a different engine version**_
_**ROSIntegration**_
_**Would you like to rebuild now**_

![Screenshot from 2019-03-20 18-01-44](https://user-images.githubusercontent.com/42842652/54687311-16da3c00-4b3d-11e9-832f-153ac0ee8cbe.png)

I click yes and then this message appears:
_**MyProject2 could not be compiled. Try rebuilding from the source manually**_
![Screenshot from 2019-03-20 18-06-05](https://user-images.githubusercontent.com/42842652/54687336-2b1e3900-4b3d-11e9-8156-ca5d1adb4f7e.png)

I click okay and unreal closes. How can this problem be fixed?

**Comment by samkys** [comment]
Did you only paste the ROSIntegration.uplugin into the ROSIntegration directory?

Is there any other files in the Plugins/ROSIntegration directory?

**Comment by kamilhassaan** [comment]
Yes. I only pasted ROSIntegration.uplugin into the ROSIntegration directory.

No. There are no other file(s) in the  Plugins/ROSIntegration directory.

These are the screenshots of the directory:

![Screenshot from 2019-03-21 09-51-26](https://user-images.githubusercontent.com/42842652/54734045-f2bf3f00-4bbe-11e9-8561-9aa339059375.png)

![Screenshot from 2019-03-21 09-51-34](https://user-images.githubusercontent.com/42842652/54734102-2e5a0900-4bbf-11e9-94b2-325c0389be3c.png)

![Screenshot from 2019-03-21 09-51-38](https://user-images.githubusercontent.com/42842652/54734110-36b24400-4bbf-11e9-9dce-44648a790220.png)

**Comment by Sanic** [comment]
Hi

1) Having no Plugins/ folder a new project is normal. You usually have to create them manually.
2) You have to put the whole repository content into the Plugins/ folder. Not only the uproject file...:
From the readme:
_Add this repository to your Plugins/ Folder in your Unreal project (**copy the folder in** so your structure looks like MyUnrealProject/Plugins/ROSIntegration/ROSIntegration.uplugin_

**Comment by samkys** [comment]
As stated above already, just make sure everything that you cloned or downloaded from github.com/code-iai/ROSIntegration is in that directory as well as the ROSIntegration.uplugin. It should work fine after that.

**Comment by kamilhassaan** [comment]
Thank you! That worked
