### ISSUE TITLE
[ERROR] Exception in deserialization of BSON - roslaunch

### ISSUE THREAD

**Issue by hassanyf** [code-iai/ROSIntegration#91]
I am getting this error when I run my simulation. 

![Screenshot_20190729_161521](https://user-images.githubusercontent.com/4363390/62055581-31739e80-b21c-11e9-8b9a-a3202c668050.png)

**Comment by Sanic** [comment]
Closed due to age/inactivity etc.
If you think this error persists, please re-open the issue.
